version: '3.3'

services:

  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - 1234:5432

  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
      - 13714
    ports:
      - 8000:8000
      - 13714:13714
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
      - /app/node_modules

    entrypoint: ./docker-entrypoint.sh
    restart: on-failure

  frontend:
    build: 
      context: .
      dockerfile: ./Dockerfile.front
    command: npm run dev
    expose:
      - 5173
    ports:
      - 5173:5173
    volumes:
      - .:/frontend
      - /frontend/node_modules
    env_file:
      - ./.env
    restart: on-failure

secrets:
  django:
    file: ./.env

volumes:
  postgres_data:
